# Version management for ZeroEQ
# This file centralizes version information

file(READ "${CMAKE_SOURCE_DIR}/VERSION" ZEROEQ_VERSION_STRING)
string(STRIP "${ZEROEQ_VERSION_STRING}" ZEROEQ_VERSION_STRING)

string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(-(.+))?$" VERSION_MATCH "${ZEROEQ_VERSION_STRING}")

if(VERSION_MATCH)
    set(ZEROEQ_VERSION_MAJOR ${CMAKE_MATCH_1})
    set(ZEROEQ_VERSION_MINOR ${CMAKE_MATCH_2})
    set(ZEROEQ_VERSION_PATCH ${CMAKE_MATCH_3})

    if(CMAKE_MATCH_5)
        set(ZEROEQ_VERSION_SUFFIX ${CMAKE_MATCH_5})
        set(ZEROEQ_VERSION_FULL "${ZEROEQ_VERSION_MAJOR}.${ZEROEQ_VERSION_MINOR}.${ZEROEQ_VERSION_PATCH}-${ZEROEQ_VERSION_SUFFIX}")
    else()
        set(ZEROEQ_VERSION_SUFFIX "")
        set(ZEROEQ_VERSION_FULL "${ZEROEQ_VERSION_MAJOR}.${ZEROEQ_VERSION_MINOR}.${ZEROEQ_VERSION_PATCH}")
    endif()
else()
    message(FATAL_ERROR "Invalid version format in VERSION file: ${ZEROEQ_VERSION_STRING}")
endif()

set(PROJECT_VERSION "${ZEROEQ_VERSION_MAJOR}.${ZEROEQ_VERSION_MINOR}.${ZEROEQ_VERSION_PATCH}")
set(PROJECT_VERSION_MAJOR ${ZEROEQ_VERSION_MAJOR})
set(PROJECT_VERSION_MINOR ${ZEROEQ_VERSION_MINOR})
set(PROJECT_VERSION_PATCH ${ZEROEQ_VERSION_PATCH})

if(NOT CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    set(ZEROEQ_VERSION ${ZEROEQ_VERSION_FULL} PARENT_SCOPE)
endif()

message(STATUS "ZeroEQ Version: ${ZEROEQ_VERSION_FULL}")
message(STATUS "  Major: ${ZEROEQ_VERSION_MAJOR}")
message(STATUS "  Minor: ${ZEROEQ_VERSION_MINOR}")
message(STATUS "  Patch: ${ZEROEQ_VERSION_PATCH}")
if(ZEROEQ_VERSION_SUFFIX)
    message(STATUS "  Suffix: ${ZEROEQ_VERSION_SUFFIX}")
endif()
